### ISSUE TITLE
oclint went wrong 

### ISSUE THREAD

**Issue by adudurant** [oclint/oclint#427]
When  I run oclint in Jenkins，it came  out the problem ， as follows
（The compile_commands.json is about 23MB）
Traceback (most recent call last):
  File "/Users/ci/webplatform-ci/oclint/build/oclint-release/bin/oclint-json-compilation-database", line 87, in <module>
    exit_code = subprocess.call(oclint_invocation, shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long

Who could help?Thanks！

**Comment by ryuichis** [comment]
Thanks for reporting this. I am closing this and hope the conversation continues at #233.

**Comment by adudurant** [comment]
In fact,I had spilted the file into smaller pieces,about less than 10MB and  it had run smoothly for a long time .However, I solved this by spitting more smaller ,for about 9MN.  Funny!

**Comment by adudurant** [comment]
@ryuichis
