### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by newfun1994** [oclint/oclint#436]
I use oclint analyzing my project. sometime it's ok. Most of the time it is failing.

```
Traceback (most recent call last):
  File "/usr/local/bin/oclint-json-compilation-database", line 64, in <module>
    file_path = get_source_path(file_item["file"], file_item["directory"])
  File "/usr/local/bin/oclint-json-compilation-database", line 27, in get_source_path
    if file_attr.startswith(os.sep):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
but `compile_commands.json` is successful

I don't know where wrong

My shell script
```
#!/bin/bash
source ~/.bash_profile
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
rm -rf compile_commands.json
rm -rf report.html
echo '*****************begin clean*****************'
xcodebuild clean -workspace ios_plugin_board.xcodeproj/project.xcworkspace -scheme ios_plugin_board
echo '*****************clean success*****************'

echo '*****************begin build*****************'
xcodebuild -workspace 'ios_plugin_board.xcodeproj/project.xcworkspace' -scheme 'ios_plugin_board' | xcpretty -r json-compilation-database -o compile_commands.json
echo '************ end building ************'

echo '************ start analyzing ************'
oclint-json-compilation-database -v \
-e ios_plugin_board/PafReactNativeSubmodule \
-e ios_plugin_board/PluginViewControllers \
-- -report-type html -o report.html \
-disable-rule=LongVariableName \
-disable-rule=ShortVariableName \
-disable-rule=LongLine \
-disable-rule=LongMethod \
-disable-rule=UseObjectSubscripting \
-disable-rule=UseContainerLiteral \
-disable-rule=UselessParentheses \
-disable-rule=UnusedMethodParameter \
-max-priority-1=10000 \
-max-priority-2=10000 \
-max-priority-3=10000
echo '*********** end analyzing ************'
```

**Comment by UnrealQuester** [comment]
This looks like a problem with the clint-json-compilation-database script or the `compile_commands.json` file.

The error seems to indicate that one of the entries in that database has a file attribute with the value `null` instead of a filepath. Can you check your `compile_commands.json` to see if this is the case?

**Comment by tianshunjian** [comment]
I met this problem too. Have you resolved it now, and how to do with it?

**Comment by newfun1994** [comment]
@tianshunjianI have not solved yet

**Comment by newfun1994** [comment]
@tianshunjian I have not solved yet

**Comment by tianshunjian** [comment]
So do you get any thing replacing OCLint?

**Comment by newfun1994** [comment]
@tianshunjian you can try Infer

**Comment by tianshunjian** [comment]
can you install Infer successfully? When I install it, Downloading https://ocaml-extlib.googlecode.com/files/extlib-1.5.3.tar.gz failed.

**Comment by ryuichis** [comment]
@newfun1994 @tianshunjian This conversation is out of topic.
