### ISSUE TITLE
fatal error: MSpanList_Insert  oclint(0.13, commit : 089e21) 

### ISSUE THREAD

**Issue by dingjingpisces2015** [oclint/oclint#469]
### Issue Summary

when excuting make on oclint/script dir, error occur

```
failed MSpanList_Insert 0xb4b318 0x18acdcbd01bf3 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x46e5c0, 0x10)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:530 +0x90
runtime.(*mSpanList).insert(0x983d48, 0xb4b318)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:933 +0x293
runtime.(*mheap).freeSpanLocked(0x983540, 0xb4b318, 0x100, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:809 +0x4be
runtime.(*mheap).grow(0x983540, 0x8, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:675 +0x2a0
runtime.(*mheap).allocSpanLocked(0x983540, 0x1, 0xb4b2a0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:553 +0x4e3
runtime.(*mheap).alloc_m(0x983540, 0x1, 0xa, 0xb4b2a0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff5fbfed08)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x983540, 0x1, 0x1000000000a, 0xeb4f)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x984c70, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x984c70, 0xb4b2a0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0xaf5000, 0xa, 0xb4b2a0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0x974d00)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:245 fp=0xc8200b2c38 sp=0xc8200b2c30
runtime.mallocgc(0x90, 0x437240, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/malloc.go:643 +0x869 fp=0xc8200b2d10 sp=0xc8200b2c38
runtime.newobject(0x437240, 0x29)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/malloc.go:781 +0x42 fp=0xc8200b2d38 sp=0xc8200b2d10
cmd/compile/internal/gc.Nod(0x5, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/subr.go:337 +0x27 fp=0xc8200b2d58 sp=0xc8200b2d38
cmd/compile/internal/gc.nodlit(0x3fa600, 0xc8201e5aa0, 0xc8201e5aa0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/const.go:1144 +0x32 fp=0xc8200b2dd0 sp=0xc8200b2d58
cmd/compile/internal/gc.(*parser).operand(0x973b80, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:1438 +0x218 fp=0xc8200b2e10 sp=0xc8200b2dd0
cmd/compile/internal/gc.(*parser).pexpr(0x973b80, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:1537 +0x48 fp=0xc8200b2ed8 sp=0xc8200b2e10
cmd/compile/internal/gc.(*parser).uexpr(0x973b80, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:1399 +0x19f fp=0xc8200b2f88 sp=0xc8200b2ed8
cmd/compile/internal/gc.(*parser).bexpr(0x973b80, 0x1, 0x973b80)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:1278 +0x25 fp=0xc8200b2fc8 sp=0xc8200b2f88
cmd/compile/internal/gc.(*parser).expr(0x973b80, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:1297 +0x33 fp=0xc8200b2ff0 sp=0xc8200b2fc8
cmd/compile/internal/gc.(*parser).arg_list(0x973b80, 0x0, 0xc820086100)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:2804 +0x77 fp=0xc8200b3018 sp=0xc8200b2ff0
cmd/compile/internal/gc.(*parser).pexpr(0x973b80, 0x100, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:1616 +0x7f fp=0xc8200b30e0 sp=0xc8200b3018
cmd/compile/internal/gc.(*parser).uexpr(0x973b80, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:1399 +0x19f fp=0xc8200b3190 sp=0xc8200b30e0
cmd/compile/internal/gc.(*parser).bexpr(0x973b80, 0x1, 0x973b88)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:1278 +0x25 fp=0xc8200b31d0 sp=0xc8200b3190
cmd/compile/internal/gc.(*parser).expr(0x973b80, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:1297 +0x33 fp=0xc8200b31f8 sp=0xc8200b31d0
cmd/compile/internal/gc.(*parser).simple_stmt(0x973b80, 0x1, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:642 +0x2d0 fp=0xc8200b3310 sp=0xc8200b31f8
cmd/compile/internal/gc.(*parser).stmt(0x973b80, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:2649 +0x6f fp=0xc8200b3398 sp=0xc8200b3310
cmd/compile/internal/gc.(*parser).stmt_list(0x973b80, 0xc8201fe2e0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:2732 +0x59 fp=0xc8200b33e0 sp=0xc8200b3398
cmd/compile/internal/gc.(*parser).loop_body(0x973b80, 0x4518e0, 0x9, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:989 +0x183 fp=0xc8200b3450 sp=0xc8200b33e0
cmd/compile/internal/gc.(*parser).if_stmt(0x973b80, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:1137 +0x121 fp=0xc8200b34b8 sp=0xc8200b3450
cmd/compile/internal/gc.(*parser).stmt(0x973b80, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:2661 +0x4a6 fp=0xc8200b3540 sp=0xc8200b34b8
cmd/compile/internal/gc.(*parser).stmt_list(0x973b80, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:2732 +0x59 fp=0xc8200b3588 sp=0xc8200b3540
cmd/compile/internal/gc.(*parser).compound_stmt(0x973b80, 0x19c501, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:926 +0xd1 fp=0xc8200b3600 sp=0xc8200b3588
cmd/compile/internal/gc.(*parser).else_(0x973b80, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:1194 +0x33 fp=0xc8200b3640 sp=0xc8200b3600
cmd/compile/internal/gc.(*parser).elseif_list_else(0x973b80, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:1181 +0x134 fp=0xc8200b3688 sp=0xc8200b3640
cmd/compile/internal/gc.(*parser).if_stmt(0x973b80, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:1139 +0x154 fp=0xc8200b36f0 sp=0xc8200b3688
cmd/compile/internal/gc.(*parser).stmt(0x973b80, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:2661 +0x4a6 fp=0xc8200b3778 sp=0xc8200b36f0
cmd/compile/internal/gc.(*parser).stmt_list(0x973b80, 0xc8201c7f60)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:2732 +0x59 fp=0xc8200b37c0 sp=0xc8200b3778
cmd/compile/internal/gc.(*parser).fnbody(0x973b80, 0x0)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:2215 +0x5d fp=0xc8200b3800 sp=0xc8200b37c0
cmd/compile/internal/gc.(*parser).hidden_import(0x973b80)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:3018 +0x178 fp=0xc8200b3928 sp=0xc8200b3800
cmd/compile/internal/gc.(*parser).hidden_import_list(0x973b80)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:3462 +0x28 fp=0xc8200b3950 sp=0xc8200b3928
cmd/compile/internal/gc.(*parser).import_there(0x973b80)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:503 +0x26 fp=0xc8200b3978 sp=0xc8200b3950
cmd/compile/internal/gc.(*parser).import_stmt(0x973b80)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:369 +0x6b fp=0xc8200b3a70 sp=0xc8200b3978
cmd/compile/internal/gc.(*parser).import_(0x973b80)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:350 +0x69 fp=0xc8200b3a98 sp=0xc8200b3a70
cmd/compile/internal/gc.(*parser).file(0x973b80)
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:316 +0x53 fp=0xc8200b3ad0 sp=0xc8200b3a98
cmd/compile/internal/gc.parse_file()
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/parser.go:56 +0x5a fp=0xc8200b3ae0 sp=0xc8200b3ad0
cmd/compile/internal/gc.Main()
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/gc/lex.go:345 +0x1d44 fp=0xc8200b3e00 sp=0xc8200b3ae0
cmd/compile/internal/amd64.Main()
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc8200b3e68 sp=0xc8200b3e00
main.main()
	/usr/local/Cellar/go/1.6.1/libexec/src/cmd/compile/main.go:32 +0x395 fp=0xc8200b3f40 sp=0xc8200b3e68
runtime.main()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc8200b3f90 sp=0xc8200b3f40
runtime.goexit()
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200b3f98 sp=0xc8200b3f90
make[2]: *** [bin/llvm-go] Error 2
make[1]: *** [tools/llvm-go/CMakeFiles/llvm-go.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

### Environment
- Operation system name and version:  macOS Sierra 10.12.6 
- OCLint version: 0.13
- How OCLint is installed: local build

### Reproduction Steps

```
cd oclint/script
./make
```

### Expected Behavior
Build oclint successfully

### Actual Behavior
Error occur

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by dingjingpisces2015** [comment]
after install ninja, problem solved
```
brew install ninja
```
