### ISSUE TITLE
Crash on Xcode 14 when used via Fastlane

### ISSUE THREAD

**Issue by ebru-backbase** [oclint/oclint#641]
### Issue Summary
Running oclint via fastlane by using xcode 14 shows a crash. Previously with xcode 13.4 and below versions, it was working without a problem.

### Environment
- Operation system name and version: macOS Monterey Version 12.6 and xCode 14.0.1
- OCLint version: 22.02
- How OCLint is installed: Via homebrew

### Reproduction Steps
Run oclint via fastlane.

#### Sample code
```
oclint(
	compile_commands: "#{ENV['DERIVED_DATA']}/compile_commands.json",
	exclude_regex: /_vers.c|Tests|Libraries|Pods|TestApp/, 
	max_priority_1: 1000,
	max_priority_2: 1000, 
	max_priority_3: 1000,
	report_type: "xml",
	report_path: "${SONAR_REPORTS_PATH}/oclint.xml",
	thresholds: ["LONG_LINE=180", "LONG_VARIABLE_NAME=45"], 
	enable_global_analysis: false
)
```

### Expected Behavior
What do you expect to happen as a result of the reproduction steps?
Expected behavior in Xcode 14 to get a success result or a failure with a list of failed items added to the `compiled_commands.json`. 

### Actual Behavior
What currently happens as a result of the reproduction steps?
It crashes after producing a lot of errors on the log, but it does not even show these errors inside the `compile_commands.json` file. 

Following is the error:

```
1 error generated.
1 error generated.
1 error generated.
9 errors generated.
1 error generated.
1 error generated.
1 error generated.
4 errors generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
9 errors generated.
1 error generated.
1 error generated.
1 error generated.
4 errors generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
1 error generated.
9 errors generated.

	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Users/ebru/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/forwardable.rb:230:in `sh'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/oclint.rb:95:in `run'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:238:in `block (3 levels) in parsing_binding'
	from Fastfile:237:in `chdir'
	from Fastfile:237:in `block (2 levels) in parsing_binding'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/gems/fastlane-2.210.1/bin/fastlane:23:in `<top (required)>'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/bin/fastlane:23:in `load'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/bin/fastlane:23:in `<main>'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/bin/ruby_executable_hooks:22:in `eval'
	from /Users/ebru/.rvm/gems/ruby-2.6.9/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by SunshineTeemo** [comment]
I also find the same  issue.

Environment
Operation system name and version: macOS Monterey Version 13.0 and xCode 14.1
OCLint version: 22.02
How OCLint is installed: Download from this website: https://github.com/oclint/oclint/releases

when I call the following command, report limitless “1 error generated”.

> oclint-json-compilation-database -e Pods -- -report-type pmd -o oclintReport.xml -rc LONG_LINE=9999 -max-priority-1=9999 -max-priority-2=9999 -max-priority-3=9999

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment]
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.
