### ISSUE TITLE
Library not loaded: @rpath/libc++.1.dylib

### ISSUE THREAD

**Issue by michaelrourke** [oclint/oclint#657]
### Issue Summary
oclint-json-compilation-database fails with Library not loaded: @rpath/libc++.1.dylib

### Environment
macOS Sequoia 15.1.1 on M1
OCLint 24.11
installed oclint-24.11-llvm-16.0.5-arm64-darwin-macos-15.1.1-xcode-16.1.tar.gz components into /usr/local

### Reproduction Steps
generate compile_commands.json
run oclint-json-compilation-database
```
dyld[15612]: Library not loaded: @rpath/libc++.1.dylib
  Referenced from: <EB515C87-2BE5-36F9-809B-6E6C3538DEDA> /usr/local/bin/oclint-23.0
  Reason: tried: '/Users/lqi/Workspaces/ryuichis/Labs/oclint/build/llvm-install/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/lqi/Workspaces/ryuichis/Labs/oclint/build/llvm-install/lib/libc++.1.dylib' (no such file), '/Users/lqi/Workspaces/ryuichis/Labs/oclint/build/oclint-core/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/lqi/Workspaces/ryuichis/Labs/oclint/build/oclint-core/lib/libc++.1.dylib' (no such file), '/Users/lqi/Workspaces/ryuichis/Labs/oclint/build/llvm-install/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/lqi/Workspaces/ryuichis/Labs/oclint/build/llvm-install/lib/libc++.1.dylib' (no such file), '/Users/lqi/Workspaces/ryuichis/Labs/oclint/build/oclint-core/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/lqi/Workspaces/ryuichis/Labs/oclint/build/oclint-core/lib/libc++.1.dylib' (no such file)

```
I tried `locate libc++.1.dylib` and it doesn't appear to be in the usual places (just iOS simulatiors).

Suggestions to resolve would be appreciated.

**Comment by ryuichi-assistant** [comment]
It seems like you have not followed our issue template.

To make it easier for us help you resolve this issue, please update the issue by following our template.

**Comment by ryuichis** [comment]
Hi @michaelrourke , I think it may be easier for you to get a copy of the source code, go to `oclint-scripts` folder and run `./make` from there. It will build a local version in `build` folder. The entire build process should be quick. Let me know how it goes.

**Comment by michaelrourke** [comment]
Thank you @ryuichis. I have built from source and I'm now getting other 
issues:

My errors now look like this:
oclint: error: Cannot change dictionary into 
"/Users/michaelr/Documents/Dev/SamuraiSafe/Common/_NameValue.m", please 
make sure the directory exists and you have permission to access!

I've checked the json. xcpretty appears to be getting confused and seems 
to be reusing source files as directories. Don't understand why...

regards
Michael

**Comment by ryuichis** [comment]
This latest issue is likely because of macos' TCC restriction.

The proper solution follows

1. Go to System Settings > Privacy & Security > Full Disk Access.
1. Click the + icon to add the path to your locally built oclint.
1. Enable the checkbox for the tool.

However, a much easier alternative is just to move your projects out of `Documents` folder to anything other than `Documents`, `Desktop`, `Downloads`, and `Pictures`.

**Comment by michaelrourke** [comment]
Hi @ryuichis

Unfortunately this doesn't appear to be the case. I have triple checked my TCC settings and they are ok.

Running oclint with dtruss (sip disabled showing open|write|stat|chdir) indicates it really is treating a file as a directory:

> open("/Users/michaelr/Library/Developer/Xcode/DerivedData/SamuraiSafe-dcztgmqxczqhpdhcunticgwcdvrr/Build/Intermediates.noindex/SamuraiSafeOSX.build/Release/SamuraiSafe AutoFill.build/Objects-normal/x86_64/_Password.d\0", 0x1000601, 0x1B6)		 = 3 0
fstat64(0x3, 0x16D0B2100, 0x0)		 = 0 0
fstat64(0x3, 0x16D0B20F0, 0x0)		 = 0 0
write(0x3, "dependencies dependencies: \\\n  /Users/michaelr/Documents/Dev/SamuraiSafe/Common/_Password.m \\\n  /Users/michaelr/Documents/Dev/SamuraiSafe/Common/SamuraiSafe-Prefix.pch \\\n  /usr/local/lib/clang/17/include/module.modulemap \\\n  /Users/michaelr/Documents/Dev/S", 0x165)		 = 357 0
open("/Users/michaelr/Library/Developer/Xcode/DerivedData/SamuraiSafe-dcztgmqxczqhpdhcunticgwcdvrr/Build/Intermediates.noindex/SamuraiSafeOSX.build/Release/SamuraiSafe AutoFill.build/Objects-normal/x86_64/_Password.dia\0", 0x1000601, 0x1B6)		 = 3 0
fstat64(0x3, 0x16D0B21D0, 0x0)		 = 0 0
fstat64(0x3, 0x16D0B2230, 0x0)		 = 0 0
write(0x3, "DIAG\001\b\0", 0xDC)		 = 220 0
chdir("/Users/michaelr/Documents/Dev/SamuraiSafe/Common/_NameValue.m\0", 0x0, 0x0)		 = -1 Err#20
write_nocancel(0x2, "\n\0", 0x1)		 = 1 0
write_nocancel(0x2, "oclint: error: \0", 0xF)		 = 15 0
write_nocancel(0x2, "Cannot change dictionary into \"/Users/michaelr/Documents/Dev/SamuraiSafe/Common/_NameValue.m\", please make sure the directory exists and you have permission to access!\0", 0xA7)		 = 167 0
write_nocancel(0x2, "\n\0", 0x1)

The compilation database (`compile_commands.json`) has entries where the 'directory' key is a file not a directory - which seems the source of the issue. In this case one entry has 
> file: /Users/michaelr/Documents/Dev/SamuraiSafe/Common/_Password.m 
directory: /Users/michaelr/Documents/Dev/SamuraiSafe/Common/_NameValue.m

Which makes no sense to me.

Michael

**Comment by SYJshang** [comment]
I have the same problem，Problems encountered after upgrading the system and xcode（macOS Sequoia 15.1.1，xcode16.1）

**Comment by SYJshang** [comment]
Traceback (most recent call last):
  File "/Users/ll/Downloads/oclint-24.11/build/oclint-release/bin/oclint-json-compilation-database", line 65, in <module>
    file_path = get_source_path(file_item["file"], file_item["directory"])
  File "/Users/ll/Downloads/oclint-24.11/build/oclint-release/bin/oclint-json-compilation-database", line 27, in get_source_path
    if file_attr.startswith(os.sep):
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'****
After I finished compiling the source code, the previous problem could be solved, but after executing the oclint-json compilation database command, this error was reported, which seems to be an issue with xcode16 xcodebulid?

**Comment by michaelrourke** [comment]
I saw this error too. This occurred with the json compilation database 
when the 'file' key was empty. In my case I filtered these out before 
hitting the aforementioned problem. It appears that there are issues 
building the json compilation database from the xcodebuild output.

Michael

**Comment by SYJshang** [comment]
> 我也看到了这个错误。当“file”键为空时，json编译数据库就会出现这种情况。在我之前遇到上述问题，我过滤掉了这些错误。看来是从 xcodebuild 构建输出 json 编译数据库存在问题。Michael
> […](#)
> 2024年12月5日 14:00，SYJ 写道：Traceback（最近一次调用最后一次）：文件“/Users/ll/Downloads/oclint-24.11/build/oclint-release/bin/oclint-json-compilation- database”，第65行，位于<module> file_path = get_source_path(file_item["file"], file_item["directory"]) 文件“/Users/ll/Downloads/oclint-24.11/build/oclint-release/bin/oclint-json-compilation-database”，第27行，位于 get_source_path 中，如果 file_attr.startswith( os.sep): ^^^^^^^^^^^^^^^^^^^^^^^ 属性错误： 'NoneType' 对象没有属性 'startswith'**** 在我完成源代码编译后，之前的问题可能已经解决了，但是执行oclint-json编译数据库命令之后报这个错误，好像是xcode16 xcodebulid的问题？--直接回复此邮件或在GitHub上查看： [#657 （评论）](https://github.com/oclint/oclint/issues/657#issuecomment-2518982979) 您此消息是因为有人提到了您。消息ID：***@***.***>

I used `jq 'map(select(.file != null))' compile_commands.json > temp.json && mv temp.json compile_commands.json `to filter, and then ran it and got a new error, telling me that I did not have file permissions. Has anyone encountered this before?
```
oclint-json-compilation-database -- -report-type pmd -o sonar-reports/oclint_result.xml

oclint: error: Cannot change dictionary into "/Users/ll/Desktop/XAW-iOS/Sonar/basiccomponents/XAWHttpApiCore/XAWHttpApiCore/Core/XAWHttpPageableApi.m", please make sure the directory exists and you have permission to access!
```

**Comment by Lianghuajian** [comment]
> ```
> Traceback (most recent call last):
>   File "/Users/ll/Downloads/oclint-24.11/build/oclint-release/bin/oclint-json-compilation-database", line 65, in <module>
>     file_path = get_source_path(file_item["file"], file_item["directory"])
>   File "/Users/ll/Downloads/oclint-24.11/build/oclint-release/bin/oclint-json-compilation-database", line 27, in get_source_path
>     if file_attr.startswith(os.sep):
>        ^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'startswith'****
> ```
> 
> After I finished compiling the source code, the previous problem could be solved, but after executing the `oclint-json compilation` database command, this error was reported, which seems to be an issue with xcode16 xcodebulid?
This error can try the oclint version below . Fix by @sanjin123
```
git clone -b support_Xcode16 https://github.com/Lianghuajian/oclint.git oclint 

cd oclint/oclint-scripts && ./make && cd .. 
```

**Comment by ryuichi-assistant** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by michaelrourke** [comment]
I now have success with XCode 16.2 on arm using the  @Lianghuajian build above, abandoning `xcpretty`, and using the `llvm` `-gen-cdb-fragment-path` flag instead to generate the JSON compilation database directly (see [generate-xcode-compilation-database.md](https://gist.github.com/T1T4N/f4d63a44476eb5c7046cc561cb8c7f77)). 

This method should in theory be less error prone, however you may have to deal with multiple copies of `.json` files for each source file depending on your XCode build options. The static analyser creates an extra copy, as do builds for multiple hardware platforms. Filtering the appropriate `.json` files and creating the `compile_commands.json` isn't difficult.
